### ISSUE TITLE
The weather screen doesn't work

### ISSUE THREAD

**Issue by okko132** [GeekMagicClock/smalltv-ultra#10]
![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/26894520/8ca41db4-fb9c-4150-9204-d850cc400498)

When I manually select the weather screen, everything shows zero. 
If you go to today and select the weather screen, it will appear normally. This seems to be a bug.
Only today's screen seems to be calling the API, please fix it.

**Comment by GeekMagicClock** [comment]
Hi, yes, this related to #9 , please try the v9.0.17.
