### ISSUE TITLE
Standalone mode

### ISSUE THREAD

**Issue by dsiens** [GeekMagicClock/smalltv-ultra#108]
Hello !
A standalone mode would be great, when no WiFi can be used. To use as a picture display only for example.

Would be like this : after 1 minute AP info display, turn into picture display only mode. Setting to choose to leave AP on or off in setting page.

Thanks

**Comment by ifengchao** [comment]
Hello, if you have updated to the latest version, it is supported already, please check.

**Comment by GeekMagicClock** [comment]
Hello, if you have updated to the latest version, it is supported already, please check.
