### ISSUE TITLE
Feature Request:  Bitcoin / Stock Ticker

### ISSUE THREAD

**Issue by DruidSmith** [GeekMagicClock/smalltv-ultra#11]
This is a suggestion for future enhancement - allow users to specify a set of crypto coins or stock ticker symbols and display the results as one of the rotating screens.  I've seen a version of the hardware that does this.

**Comment by 19201003080114** [comment]
PRO version can do that
https://github.com/GeekMagicClock/smalltv-pro

**Comment by GeekMagicClock** [comment]
Yes, that's feature of smalltv-pro.

**Comment by rube-de** [comment]
> Yes, that's feature of smalltv-pro.

so ultra is below pro?
