### ISSUE TITLE
Phenomenon of Not Being Able to Connect When Multiple Routers Have the Same SSID

### ISSUE THREAD

**Issue by Tagger9110** [GeekMagicClock/smalltv-ultra#2]
My English skills are limited, so I used a translation app, which may result in the sentences not being very smooth. I apologize.

Currently, the router setup consists of three routers with the same SSID, each operating on a different channel. When I performed a SCAN on the GIFTV network settings page, all three routers were detected. However, I was unable to establish a connection despite selecting one of them.

I can connect normally to other routers that do not have the same SSID.

thank you.

Ultra - V9.0.8

**Comment by GeekMagicClock** [comment]
Hi, Same SSID should not be the reason, but the settings of the WiFi may cause the problem, do you have some details of the SSID, like encryption, authentication etc.

**Comment by GeekMagicClock** [comment]
Please update to v9.0.23 to check, wifi connection has been optimized then, and if needed, please reopen issue.
