### ISSUE TITLE
Gif stops animating

### ISSUE THREAD

**Issue by mawar108** [GeekMagicClock/smalltv-ultra#28]
I dont see a setting to let looping gifs, so it would be nice if there would be a option to do that :D because now a gif what is only "5 sec" long and the display time is longer it would be stop animating after 5 secs or is it a bug ? ^^"

**Comment by GeekMagicClock** [comment]
OK, I'll check it out, thanks for reporting~

**Comment by GeekMagicClock** [comment]
I reproduced this problem when setting up a loop between themes. If you only have one gif file, it is recommended that you "set" the gif, and it will continue to play the gif file in a loop without stopping.

**Comment by mawar108** [comment]
i thought so... but isnt it possible to let it loop even with this combination of settings?

**Comment by GeekMagicClock** [comment]
> i thought so... but isnt it possible to let it loop even with this combination of settings?

Not available for now.

**Comment by Ashwagada** [comment]
> I dont see a setting to let looping gifs, so it would be nice if there would be a option to do that :D because now a gif what is only "5 sec" long and the display time is longer it would be stop animating after 5 secs or is it a bug ? ^^"

Good idea.

**Comment by GeekMagicClock** [comment]
Hi, please update to v9.0.20, if the play interval in the album theme is longer than the loop theme interval, the gif will still be played, you can try and please let me know, thank you.

**Comment by GeekMagicClock** [comment]
Reopen if needed.
