### ISSUE TITLE
Display artifact with V9.0.18

### ISSUE THREAD

**Issue by 19201003080114** [GeekMagicClock/smalltv-ultra#29]
City: North York, Canada
City code: 6091104
Firmware: V9.0.18

![IMG_0701](https://github.com/GeekMagicClock/smalltv-ultra/assets/158797249/e38172c8-798c-4cec-9241-600c4613a40f)

**Comment by TrueLoonix** [comment]
Your location gives no artifacts on my device.
Does it give the same glitch in other locations?
Did you try to re-flash your ultra?

https://github.com/GeekMagicClock/smalltv-ultra/assets/92674519/24f1e2da-dcd9-4d58-8513-4ce07bd42abc

**Comment by GeekMagicClock** [comment]
Hi, @19201003080114  that would happen randomly because of little ram, a reboot will recover. I can try to optimize the ram in future verion.

**Comment by GeekMagicClock** [comment]
@19201003080114 Hello, please try the latest firmware, if still exists, please reopen issue, thank you.
