### ISSUE TITLE
How to update firmware

### ISSUE THREAD

**Issue by Ogsmoketho92** [GeekMagicClock/smalltv-ultra#33]
Hello, I'm having trouble downloading the firmware. when I click on the ".bin" file it just shows a bunch of symbols. I've been using using my phone,should I maybe use a computer?....How exactly do I download it?

**Comment by GeekMagicClock** [comment]
Hi, this is a google drive link, you could download it here.
https://drive.google.com/drive/folders/1rTVwUcpZ8jyc81Hvls_M1WkLY-vxEryc?usp=drive_link

**Comment by Ogsmoketho92** [comment]
Nice,Thank you!
