### ISSUE TITLE
Can't change location?

### ISSUE THREAD

**Issue by Paul12345666** [GeekMagicClock/smalltv-ultra#35]
I cannot change the location of the weather app, it lets me check my connection every time I input a new one. Plus my GIF doesn't work in the main page.

**Comment by GeekMagicClock** [comment]
Hi, show me your settings on the web?

**Comment by Paul12345666** [comment]
![Screenshot 2024-04-10 at 8 59 12 PM](https://github.com/GeekMagicClock/smalltv-ultra/assets/40490855/ba4588cc-5127-4cc3-93db-3c7aca5fd4a2)

**Comment by GeekMagicClock** [comment]
Hi, where did you get it? The chinese version only support cities in China, you may need return and refund.

**Comment by Paul12345666** [comment]
I did get this in China, and I'm sure this location that I entered is in China, why it doesn't work? I'm in China right now but am I not able to update the firmware?

**Comment by GeekMagicClock** [comment]
> I did get this in China, and I'm sure this location that I entered is in China, why it doesn't work? I'm in China right now but am I not able to update the firmware?

Do not update it.  It's not compatible.

If the device is in China, please go ask for the saler's help, here's for English only.
And that should be a network issue, It's also easy to clarify, try a different network.
