### ISSUE TITLE
Manual Restart Using Web UI

### ISSUE THREAD

**Issue by PuTaTuo** [GeekMagicClock/smalltv-ultra#37]
I permernently connect a power supply to the device than just realized that there is no way to restart unless the battery runs out. It would be very convenient to have a restart button in the Web UI.

**Comment by GeekMagicClock** [comment]
Hi, there should be a "REBOOT" button in the "system" web page.

**Comment by PuTaTuo** [comment]
> Hi, there should be a "REBOOT" button in the "system" web page.

Oh I just found it. Thanks!
