### ISSUE TITLE
Multilingualism

### ISSUE THREAD

**Issue by Ashwagada** [GeekMagicClock/smalltv-ultra#43]
Hello,

If you have no idea for multilingualism, maybe it's worth temporarily using a ready-made solution?

Support for 46 languages.
https://openweathermap.org/current#multi

Just use the "lang" parameter and add a language selection field on the management page.

**Comment by GeekMagicClock** [comment]
Hello, I have check it before, that lang is not fully compeleted, some city name will be returned as still in English.
And most important part is there's little space to hold all languages.
