### ISSUE TITLE
"Thunderstorm" weather condition does not have space to display

### ISSUE THREAD

**Issue by rwkyyy** [GeekMagicClock/smalltv-ultra#57]
![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/13552349/ef85ec8a-1191-476c-a875-67467cc027d6)

**Comment by GeekMagicClock** [comment]
Thank you for report, will fix it in next updates.

**Comment by GeekMagicClock** [comment]
@rwkyyy Hello, please update to v9.0.23, thank you for report.
