### ISSUE TITLE
How to switch the english language?

### ISSUE THREAD

**Issue by samsonadmin** [GeekMagicClock/smalltv-ultra#6]

**Comment by GeekMagicClock** [comment]
Hi, English only as descripted.

**Comment by samsonadmin** [comment]
Oh actually, I wanted it to be English, however after flashing to latest, the Web interface is still in Chinese

**Comment by GeekMagicClock** [comment]
> Oh actually, I wanted it to be English, however after flashing to latest, the Web interface is still in Chinese

 I'm afraid you have to ask for return and exchange the right one.
