### ISSUE TITLE
Screen error

### ISSUE THREAD

**Issue by Gadgetuser2000** [GeekMagicClock/smalltv-ultra#60]
Hello,

i received the small-tv ultra today. after setting it up, i played with the pictures a bit. after saving, i now have an error on the screen. this error is only displayed with the theme “weather clock today”. i then deleted all the pictures in picture management. nevertheless, part of the spaceman is displayed.

Somewhere in the cache is still the image file.

What can i do?

greetings
gadgetuser
![ezgif-2-95b4e3929a](https://github.com/GeekMagicClock/smalltv-ultra/assets/169561108/42e6df8d-ef70-42b0-80f9-caf9ba261120)

**Comment by GeekMagicClock** [comment]
Hello, the wrong size gif is uploaded under the weather , please check the size, should be 80x80px, not the 240x240px



At 2024-05-12 05:50:24, "Gadgetuser2000" ***@***.***> wrote:

Hello,

i received the small-tv ultra today. after setting it up, i played with the pictures a bit. after saving, i now have an error on the screen. this error is only displayed with the theme “weather clock today”. i then deleted all the pictures in picture management. nevertheless, no part of the spaceman is displayed.

greetings
gadgetuser
ezgif-2-95b4e3929a.gif (view on web)

**Comment by Gadgetuser2000** [comment]
Thanks
