### ISSUE TITLE
Local management via HTTPS

### ISSUE THREAD

**Issue by Ashwagada** [GeekMagicClock/smalltv-ultra#61]
Hi,

Can you add "Local management via HTTPS:" like on routers?
![IMG_20240515_072834](https://github.com/GeekMagicClock/smalltv-ultra/assets/165925449/aa719473-8e89-4fd9-aebe-4e9e4f8034d7)
So with this option enabled, the configuration page should redirect to https://.

**Comment by GeekMagicClock** [comment]
Sorry, this will not be implemented on this little device, with such limited ram.
