### ISSUE TITLE
Simple weather clock bug

### ISSUE THREAD

**Issue by dudusandi** [GeekMagicClock/smalltv-ultra#65]
The clear/cloud text is inside moon/sun image in the latest update 9.0.22

**Comment by dudusandi** [comment]
![WhatsApp Image 2024-05-22 at 02 25 38](https://github.com/GeekMagicClock/smalltv-ultra/assets/41707380/58acbba6-bfc2-4fb4-8ef6-0d7946f0ce1e)

**Comment by GeekMagicClock** [comment]
Hello, this should be fixed in v9.0.23, please check, thank you for report.
