### ISSUE TITLE
Gif not updated

### ISSUE THREAD

**Issue by DerSarco** [GeekMagicClock/smalltv-ultra#66]
Hello! i was updating my SmalTv Ultra to the latest firmware, after that i wanted to change the gif that the screen display at the weather view. I cleaned the files because i didn't have enough ROM to store a new gif, but after uploading the gif, the screen doesn't show it anymore. I used the gifs at 80x80 that you have in a repository. i miss my astronaut :(

![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/64336008/c48c69f9-faac-4f77-90a0-6f76f5202594)

**Comment by ticsi** [comment]
I had a similar issue with the latest firmware. I'm looping between a full screen gif and the weather display with the small gif. After around 20 minutes or so, both gifs stop showing up. If I reboot, it works again.

(Also, if I set this automatic switching of the screens, the full-screen gif only plays once, then freezes. I'd like it to loop until the screens change.)

**Comment by GeekMagicClock** [comment]
@DerSarco  Have you upload a new gif to the weather options, not under the photo album option.

@ticsi  V9.0.22 right ?

**Comment by ticsi** [comment]
> @ticsi V9.0.22 right ?

Yes, that's right, I've updated today.

![Screenshot_20240523-165834522 (1)](https://github.com/GeekMagicClock/smalltv-ultra/assets/32036814/8b716a70-9c8c-4ae4-9f24-0d5450047cdd)

**Comment by DerSarco** [comment]
> @DerSarco Have you upload a new gif to the weather options, not under the photo album option.

Yes, i updated to the last firmware also. But the gif it doesn't display. I tried uploading to the photos section, just to test, but is the same, nothing is shown.

**Comment by GeekMagicClock** [comment]
> > @DerSarco Have you upload a new gif to the weather options, not under the photo album option.
> 
> Yes, i updated to the last firmware also. But the gif it doesn't display. I tried uploading to the photos section, just to test, but is the same, nothing is shown.

Show me your file list please.

**Comment by DerSarco** [comment]
> > > @DerSarco Have you upload a new gif to the weather options, not under the photo album option.
> > 
> > 
> > Yes, i updated to the last firmware also. But the gif it doesn't display. I tried uploading to the photos section, just to test, but is the same, nothing is shown.
> 
> Show me your file list please.

It's weird, because i upload the image, the ROM is used but i don't have a list of images.

![Screenshot 2024-05-24 at 8 41 21 AM](https://github.com/GeekMagicClock/smalltv-ultra/assets/64336008/b023e1f0-8255-4ace-8bf0-ef22b20cc6ae)

![Screenshot 2024-05-24 at 8 41 32 AM](https://github.com/GeekMagicClock/smalltv-ultra/assets/64336008/2b1d2dcf-4b36-46cf-b4be-ebd1a190751d)

**Comment by GeekMagicClock** [comment]
Hello, can you try the newest firmware V9.0.23, and also could you please provide the file with the same name you uploaded, I can try on my side.

**Comment by DerSarco** [comment]
> @ticsi @DerSarco Hello, can you try the newest firmware V9.0.23, and also @DerSarco could you please provide the file with the same name you uploaded, I can try on my side.

Ok, i'll try. The files that i used are the next ones ->

![spaceman](https://github.com/GeekMagicClock/smalltv-ultra/assets/64336008/1c342075-41ad-48b0-8f77-1c0746a02cc3)
![rem](https://github.com/GeekMagicClock/smalltv-ultra/assets/64336008/6118d665-0126-4e3c-8145-c973b6736044)
![pedro-ezgif com-cut](https://github.com/GeekMagicClock/smalltv-ultra/assets/64336008/07a15def-3195-4a13-9fa6-c7b09b862f4e)

**Comment by DerSarco** [comment]
Ok, i updated to the .23 version, i cleared the files from pictures and weather, i uploaded the spaceman again but it doesn't work. i'm crying inside 😢

**Comment by GeekMagicClock** [comment]
@DerSarco 
![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/143304545/eaf72072-91d0-4ade-a9e8-b2b7cb31b478)
OK, have you click the "SET" button?

**Comment by DerSarco** [comment]
Ok, i needed to refresh the page to see the set button. Awesome, now that's working! thanks!
