### ISSUE TITLE
feat: gif mode without wifi

### ISSUE THREAD

**Issue by JBUinfo** [GeekMagicClock/smalltv-ultra#79]
I always have gif mode enabled and I don't see the reason for it to be connected to the internet. There could be an option to not connect it to a wifi and have the user go directly to gif mode (via the device's own wifi).

**Comment by GeekMagicClock** [comment]
Hi, thanks for your advice.
That feature has been added since V9.0.22.

5) Feature：Photo album theme could work without internet connected. [AP "GIFTV" will start for 1 minute after power on, if there's no clients connected, the "GIFTV" will be closed.]
