### ISSUE TITLE
Forcast screen is broken

### ISSUE THREAD

**Issue by 19201003080114** [GeekMagicClock/smalltv-ultra#9]
In weather forecast screen:
- Time display at the top is broken when minute is between :00 to :09 (In picture time is 12:09)
- Third day forecast at the bottom is not displayed

![IMG_0399](https://github.com/GeekMagicClock/smalltv-ultra/assets/158797249/15f8f042-0b32-424a-bd6e-e8486ce70d3f)

**Comment by 19201003080114** [comment]
Example city is Toronto, Canada (6167865)

**Comment by GeekMagicClock** [comment]
Hello, is that the latest firmware ?

**Comment by amomesso** [comment]
> Hello, is that the latest firmware ?

No, I bought it in November/December. Is there a way to find out what version is currently installed?

**Comment by 19201003080114** [comment]
I use latest firmware. V9.0.15

**Comment by netstx** [comment]
> Hello, is that the latest firmware ?

I have the same issue and I'm using latest firmware.

![Screenshot_20240302-152359.png](https://github.com/GeekMagicClock/smalltv-ultra/assets/8229460/9bf54a37-9f03-4e8a-8396-380f554ad52d)

Thanks!

**Comment by 19201003080114** [comment]
Ultra latest is V9.0.15 in GitHub

![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/158797249/998c4360-6d7f-42de-b676-8c441e60278c)

**Comment by amomesso** [comment]
I updated to the last version but it does not fix the bug.
Also i don't know how @netstx can see firmware version. 
![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/92845421/6a111204-d601-49de-8e36-08cf7d8826a7)

**Comment by DruidSmith** [comment]
Same issue, I am also on 9.0.16.  Forecast only shows next two days and does not apply the units setting (values only come up as celsius).

It would be nice if the developer posted the source code so that others could help contribute.

**Comment by jaaxx** [comment]
Can confirm.  Third day has null info and the units (C vs F) do not respect the settings.

**Comment by ferrellsl** [comment]
I have the same problem under 9.0.16.

**Comment by GeekMagicClock** [comment]
Thank you all for this report, please update to 9.0.17, this bug has been fixed, and the Min and Max temperature of the day has been fixed too!

**Comment by ferrellsl** [comment]
> Thank you all for this report, please update to 9.0.17, this bug has been fixed, and the Min and Max temperature of the day has been fixed too!

Thanks for the fix/update.  I have three SmallTV-Ultras and confirm that this fix works on all three devices.  For others applying this update, the forecast screen will update after a few minutes.  Just apply the update and wait 20 minutes for the forecast screen to update.

**Comment by ferrellsl** [comment]
There's still the issue of the forecast screen not showing Fahrenheit temperatures but I'm still grateful for the progress.  Thank you for creating such a cool little weather station.

**Comment by GeekMagicClock** [comment]
Please update to V9.0.18, thank you all~

**Comment by ferrellsl** [comment]
> Please update to V9.0.18, thank you all~

Confirmed, working properly on all 3 of my devices Fahrenheit temperatures work properly now on the forecast screen.  Thank you for your hard work and for making such a cool little weather station.
