### ISSUE TITLE
Problem in upload gifs

### ISSUE THREAD

**Issue by RTormente** [GeekMagicClock/smalltv-ultra#94]
On my smalltv-ultra and I can't upload gifs.

When I try to upload gifs with 1MB or more, smalltv-ultra crashes, and the upload takes a long time, when finished it shows the file with 0MB and it is not possible to view it.

![image](https://github.com/user-attachments/assets/a94c2c6c-8256-420f-bcd1-2368d9a3c9b6)
![image](https://github.com/user-attachments/assets/d7ced453-9f06-4ae0-8786-83faa80956df)
![image](https://github.com/user-attachments/assets/68532437-26c0-4243-a9a7-632a7cb2a4da)

I pressed to clear the files but it didn't work, I tried with the gifs from the GeekMagicClock/gif/gif 240x240px repository and the same thing happened.
I updated the firmware from V9.0.25 to V9.0.26 and I performed the factory reset but I still have the same error.

![image](https://github.com/user-attachments/assets/a6356381-f838-412f-8949-3c318fec10fa)

Also, I don't know if it's normal, but no image appears for the weather status

![Imagem do WhatsApp de 2024-07-18 à(s) 01 30 49_7c60e2fe](https://github.com/user-attachments/assets/64e99551-a3c5-4620-a2c7-389eca240f21)

**Comment by RTormente** [comment]
I forgot to mention that I also performed the factory reset and besides what I mentioned, I don't know if it's normal for an image to not appear for the weather status.

![Imagem do WhatsApp de 2024-07-18 à(s) 01 30 49_7c60e2fe](https://github.com/user-attachments/assets/b694303e-3b5a-4c3a-88b1-790ecf7e32d0)

**Comment by GeekMagicClock** [comment]
Hello,
1. Please check the free space before uploading, your free space shows 479KB, so if you upload more than that, yes it will fail.
2. The gray circle icon on the top right corner means clear at night.
Thank you.

**Comment by RTormente** [comment]
I really didn't realize
sorry
