### ISSUE TITLE
Weather screen

### ISSUE THREAD

**Issue by ninja1a** [GeekMagicClock/smalltv-ultra#98]
Suddenly dropped info on weather page
Gui still works
The code for location shows ok but no weather page info
![image](https://github.com/user-attachments/assets/6ce72939-081f-43b3-ab52-fea121360bb3)
Can anyone say what to do
I have updated firmware and still same
I have factory reset
And still same

**Comment by VaultBoy88** [comment]
Same on my devices as well. Api change?

**Comment by vlgrilo** [comment]
Same on my devices

**Comment by vlgrilo** [comment]
Same on my devices
![1](https://github.com/user-attachments/assets/89ddc225-00ef-49d1-9818-7e57d796bbef)
![2](https://github.com/user-attachments/assets/dd8816c7-362f-4eaf-a2c6-bfb28812c1b1)

**Comment by sodfy16** [comment]
Same problem here. I did a packet capture on a device with `Ultra-V9.0.26` firmware;
Two requests are sent - and weather data collected from two _different_ providers:

**Current weather**
`GET http://api.openweathermap.org:80/data/2.5/weather?id={MY_CITY_ID}&appid={MY_API_KEY}&units=metric&lang=en HTTP/1.1\r\n`
The response is a `200 OK` and includes the current weather.

**Forecast (the issue at hand)**
`GET http://api.weatherapi.com:80/v1/forecast.json?key=26934d27353840eb95a93640242505&q=57.01,10.06&days=3&aqi=no&alerts=no`
The response is a `403 FORBIDDEN` with reason `/error/message:API key has reached maximum calls per month allowed limit.`

Notice that the key used for the forecast is not our _individual_ Openweathermap one, but a hardcoded key to weatherapi.com.
My guess is that all products use the same key for the forecast - and it is one without a paid plan and thus limited to 1M calls per month ([source](https://www.weatherapi.com/pricing.aspx)).
So, we'll all have our forecasts tomorrow August 1st, and the issue will reappear near the end of each month until fixed.

![pc](https://github.com/user-attachments/assets/832a4d7a-60a9-4a66-a166-eb2f75ac8b72)

**Comment by GeekMagicClock** [comment]
> Same problem here. I did a packet capture on a device with `Ultra-V9.0.26` firmware; Two requests are sent - and weather data collected from two _different_ providers:
> 
> **Current weather** `GET http://api.openweathermap.org:80/data/2.5/weather?id={MY_CITY_ID}&appid={MY_API_KEY}&units=metric&lang=en HTTP/1.1\r\n` The response is a `200 OK` and includes the current weather.
> 
> **Forecast (the issue at hand)** `GET http://api.weatherapi.com:80/v1/forecast.json?key={KEY}"&q=57.01,10.06&days=3&aqi=no&alerts=no` The response is a `403 FORBIDDEN` with reason `/error/message:API key has reached maximum calls per month allowed limit.`
> 
> Notice that the key used for the forecast is not our _individual_ Openweathermap one, but a hardcoded key to weatherapi.com. My guess is that all products use the same key for the forecast - and it is one without a paid plan and thus limited to 1M calls per month ([source](https://www.weatherapi.com/pricing.aspx)). So, we'll all have our forecasts tomorrow August 1st, and the issue will reappear near the end of each month until fixed.

Yes, your analysis is correct, but we have paid plans, seems still run out and get 403 response,  Augest 1th will be recover. So I edit the KEY part, please don't post any key here public. And in future versions, we may offer another key input option too.

**Comment by ninja1a** [comment]
All mine came back as said

**Comment by Lozman2962** [comment]
> Again the same problem, the forecast page does not update info, the rest of the weather pages work properly.
> 
> Anyone with the same problem?


Same thing here, since maybe 2 days ago.
I thus made a free account at openweathermap.org. 
Used my personal API key, added it like 15hrs ago, still nothing.
If i make an account at weatherapi.com and input my API key this will not work right? since its hardcoded.
Thanks for anymore help :)

jf
